### ISSUE TITLE
RaftTest.scala fails on travis but not on dev machines

### ISSUE THREAD

**Issue by phiros** [leanovate/akka-typed-raft#1]
The sbt and scala version seems to be up to date  on the travis build node.

`[info] - should become a follower if a heartbeat is received *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: received unexpected message VoteRequest(3)
[info]   at scala.Predef$.assert(Predef.scala:219)
[info]   at akka.typed.testkit.scaladsl.TestProbe.expectNoMsg_internal(TestProbe.scala:209)
[info]   at akka.typed.testkit.scaladsl.TestProbe.expectNoMsg(TestProbe.scala:205)
[info]   at de.leanovate.raft.RaftTest.$anonfun$new$44(RaftTest.scala:252)
[info]   at scala.collection.Iterator.foreach(Iterator.scala:929)
[info]   at scala.collection.Iterator.foreach$(Iterator.scala:929)
[info]   at scala.collection.parallel.immutable.ParHashSet$ParHashSetIterator.foreach(ParHashSet.scala:77)
[info]   at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:970)
[info]   at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
`

full log:
* https://travis-ci.org/leanovate/akka-typed-raft/builds/331541162

**Comment by phiros** [comment]
Resolved by bd9ebac
